# ScripTeam Development Docker Compose Configuration
# Complete setup for React web PoC development
# Usage: docker-compose up -d

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: scripteam-postgres
    environment:
      POSTGRES_DB: scripteam
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d scripteam"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: scripteam-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # API Backend
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile.simple
    container_name: scripteam-api
    environment:
      - NODE_ENV=development
      - PORT=3001
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/scripteam
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=scripteam
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=dev-secret-key
      - FRONTEND_URL=http://localhost:5173
    ports:
      - "3001:3001"
    volumes:
      - ./apps/api/src:/app/apps/api/src
      - ./packages/shared:/app/packages/shared
      - upload_data:/app/uploads
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3001/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  # React Web Frontend
  web:
    build:
      context: apps/web
      dockerfile: Dockerfile.dev
    container_name: scripteam-web
    environment:
      - VITE_API_URL=http://localhost:3001
      - NODE_ENV=development
    ports:
      - "5173:5173"
    volumes:
      - ./apps/web/src:/app/src
      - ./apps/web/public:/app/public
      - ./apps/web/index.html:/app/index.html
      - ./apps/web/package.json:/app/package.json
    restart: unless-stopped
    depends_on:
      - api

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  upload_data:
    driver: local

networks:
  default:
    name: scripteam-network