# Testing Docker Compose Configuration
# Simplified setup for testing Story 1.2 progress
# Usage: docker-compose -f docker-compose.test.yml up

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: scripteam-postgres-test
    environment:
      POSTGRES_DB: scripteam_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d scripteam_test"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: scripteam-redis-test
    ports:
      - "6379:6379"
    volumes:
      - redis_test_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # API Backend
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile.simple
    container_name: scripteam-api-test
    environment:
      - NODE_ENV=development
      - PORT=3001
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/scripteam_test
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=test-secret-key
      - CORS_ORIGIN=http://localhost:8081
    ports:
      - "3001:3001"
    volumes:
      - ./apps/api/src:/app/apps/api/src
      - ./packages/shared:/app/packages/shared
      - upload_test_data:/app/uploads
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3001/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  # Mobile/Web Frontend (Expo Web)
  mobile:
    build:
      context: .
      dockerfile: apps/mobile/Dockerfile.simple
    container_name: scripteam-mobile-test
    environment:
      - EXPO_PUBLIC_API_URL=http://localhost:3001/api
      - NODE_ENV=development
    ports:
      - "8081:8081"
    volumes:
      - ./apps/mobile/src:/app/apps/mobile/src
      - ./apps/mobile/assets:/app/apps/mobile/assets
    restart: unless-stopped
    depends_on:
      - api

volumes:
  postgres_test_data:
    driver: local
  redis_test_data:
    driver: local
  upload_test_data:
    driver: local

networks:
  default:
    name: scripteam-test-network